# Generated by Django 6.1 on 2026-08-19 12:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Submission",
            new_name="QuizSubmission",
        ),
    ]
