# Generated by Django 5.2.5 on 2025-09-06 11:47

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='referred_by',
        ),
        migrations.AlterField(
            model_name='newuser',
            name='alcherid',
            field=models.TextField(blank=True, default=users.models.create_new_ref_number, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='referred_by',
            field=models.TextField(blank=True, null=True),
        ),
    ]
