"""
Django settings for caportal project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import sys
from pathlib import Path

import dj_database_url
from django.contrib.messages import constants as messages
from dotenv import load_dotenv

# Load .env file so EMAIL_HOST_USER, EMAIL_HOST_PASSWORD etc. are available
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, os.path.join(BASE_DIR, "apps"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
PROD = os.environ.get("prod", "false").lower() == "true"
if PROD:
    SECRET_KEY = os.environ.get("SECRET_KEY")
else:
    SECRET_KEY = "django-insecure-fuv21z*#t8sh)%!!!^-aso7lx+3nv1*fo8(pr(j5-5+0xd2hv9"

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = not os.environ.get('DEBUG')
DEBUG = True
ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",
    "apps.users",
    "apps.api",
    "apps.dashboard",
    "apps.submissions",
    "crispy_forms",
    "phonenumber_field",
    "mathfilters",
    "rest_framework",
    "minio_storage",
    "import_export",
    "crispy_bootstrap4",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "caportal.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "caportal.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

if not PROD:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    DATABASES = {"default": dj_database_url.config(conn_max_age=600, ssl_require=False)}

# Setup Messages
MESSAGE_TAGS = {
    messages.DEBUG: "secondary",
    messages.INFO: "info",
    messages.SUCCESS: "success",
    messages.WARNING: "warning",
    messages.ERROR: "error",
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTH_USER_MODEL = "users.NewUser"
CRISPY_TEMPLATE_PACK = "bootstrap4"
# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

LOGOUT_REDIRECT_URL = "dashboard_page"
LOGIN_URL = "/users/login/"
# Setup Email
# Gmail SMTP configuration
EMAIL_HOST = "smtp.gmail.com"
EMAIL_USE_TLS = True
EMAIL_PORT = 587

EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL") or EMAIL_HOST_USER

# Send mail through the configured SMTP server. Set EMAIL_BACKEND explicitly to
# django.core.mail.backends.console.EmailBackend only when local console output
# is desired.
EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend"
)
EMAIL_TIMEOUT = 30
# Setup Static

# Added / in static
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

# Setup Media
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"


# Minio Storage
if PROD:
    DEFAULT_FILE_STORAGE = "minio_storage.storage.MinioMediaStorage"
    STATICFILES_STORAGE = "minio_storage.storage.MinioStaticStorage"
    MINIO_STORAGE_ENDPOINT = os.environ.get("minio_endpoint")
    MINIO_STORAGE_ACCESS_KEY = os.environ.get("minio_access")
    MINIO_STORAGE_SECRET_KEY = os.environ.get("minio_secret")
    MINIO_STORAGE_USE_HTTPS = True
    MINIO_STORAGE_MEDIA_BUCKET_NAME = "alcherca27media"
    MINIO_STORAGE_AUTO_CREATE_MEDIA_BUCKET = True
    MINIO_STORAGE_STATIC_BUCKET_NAME = "alcherca27static"
    MINIO_STORAGE_AUTO_CREATE_STATIC_BUCKET = True
    print(f"PROD is True")
    print(f"MINIO_STORAGE_ENDPOINT: {MINIO_STORAGE_ENDPOINT}")

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
SECURE_REFERRER_POLICY = "no-referrer-when-downgrade"

if PROD:
    # CSRF and CORS settings
    CSRF_TRUSTED_ORIGINS = [
        "https://caportal.alcheringa.co.in",
        "https://ambassador.alcheringa.co.in",
    ]

    SESSION_COOKIE_DOMAIN = ".alcheringa.co.in"  # Note the leading dot
    CSRF_COOKIE_DOMAIN = ".alcheringa.co.in"

    # Security settings for HTTPS
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True

    # Session settings
    SESSION_COOKIE_AGE = 3600  # 1 hour
    SESSION_EXPIRE_AT_BROWSER_CLOSE = True
    SESSION_SAVE_EVERY_REQUEST = False

    # Logout redirect
    LOGOUT_REDIRECT_URL = "/"
    LOGIN_REDIRECT_URL = "/"

    # Additional security headers
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

else:
    # Development settings
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": True,
        },
        "minio_storage": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": True,
        },
        # Optionally add the root logger to catch unhandled logs
        "": {
            "handlers": ["console"],
            "level": "DEBUG",
        },
    },
}
